name: JIRENGU_CI

on:
  pull_request:
    branches:
      - main
jobs:
  homework-judgement:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment on PR
        uses: mshick/add-pr-comment@v2
        with:
          message: |
              **Thanks for your pr!**
          proxy-url: https://add-pr-comment-proxy-94idvmwyie-uc.a.run.app    
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test with Maven
        run: mvn -B clean verify --file pom.xml

      - name: Comment PR with test result
        uses: mshick/add-pr-comment@v2
        with:
          message: |
              **Your code passed the jugdement!**
          message-failure: |
            Uh oh!
          proxy-url: https://add-pr-comment-proxy-94idvmwyie-uc.a.run.app 
      - name: Set TEST_RESULT environment variable
        run: echo "TEST_RESULT=Success" >> $GITHUB_ENV
        if: ${{ success() }}

      - name: Set TEST_RESULT environment variable
        run: echo "TEST_RESULT=Failed" >> $GITHUB_ENV
        if: ${{ failure() }}
